#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys

try:
  from core import app
except ImportError:
  sys.path.append('/usr/share/mehrcal')
  print(os.getcwd())
  from core import app
    

import logging

logging.basicConfig(level=logging.DEBUG)
main = app.App()
main.run()
