#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys

try:
  from core import app
except ImportError:
  sys.path.append('/opt/mehrcal')
  os.chdir('/opt/mehrcal')
  print(os.getcwd())
  from core import app

main = app.App()
main.run()
